blank_issues_enabled: false
contact_links:
  - name: fauxpenverse @ Make WordPress.org
    url: https://make.wordpress.org/fauxpenverse/
    about: Read documentation on contributing, community, etc.
